version: "3.7"

services:
  supervisor:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
        resources:
            limits:
              cpus: '0.5'
              memory: 2G
            reservations:
              cpus: '0.2'
              memory: 125MB
    ports:
    - "8080:8080"